const {chromium}=require('@playwright/test');const fs=require('node:fs');
const base=process.env.QA_URL||'http://127.0.0.1:4190/evsavelev-web/';const label=base.startsWith('https:')?'public':'local';
(async()=>{const browser=await chromium.launch({channel:'chrome'});const runs=[];
for(let run=1;run<=3;run++){
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1});const page=await context.newPage();const session=await context.newCDPSession(page);
 await session.send('Network.enable');await session.send('Network.setCacheDisabled',{cacheDisabled:true});await session.send('Network.emulateNetworkConditions',{offline:false,latency:80,downloadThroughput:200*1024,uploadThroughput:100*1024});await session.send('Emulation.setCPUThrottlingRate',{rate:4});
 await page.addInitScript(()=>{window.qaPerf={lcp:0,lcpElement:'',cls:0,events:[],longTasks:[]};new PerformanceObserver(list=>{for(const e of list.getEntries()){qaPerf.lcp=e.startTime;qaPerf.lcpElement=e.element?.tagName||''}}).observe({type:'largest-contentful-paint',buffered:true});new PerformanceObserver(list=>{for(const e of list.getEntries())if(!e.hadRecentInput)qaPerf.cls+=e.value}).observe({type:'layout-shift',buffered:true});new PerformanceObserver(list=>{for(const e of list.getEntries())if(e.interactionId)qaPerf.events.push({name:e.name,duration:e.duration,id:e.interactionId})}).observe({type:'event',buffered:true,durationThreshold:16});new PerformanceObserver(list=>{for(const e of list.getEntries())qaPerf.longTasks.push(e.duration)}).observe({type:'longtask',buffered:true});});
 await page.goto(base,{waitUntil:'networkidle'});await page.waitForTimeout(1000);
 const initial=await page.evaluate(()=>({resources:performance.getEntriesByType('resource').map(e=>({name:e.name,bytes:e.transferSize,encoded:e.encodedBodySize})),document:performance.getEntriesByType('navigation')[0].transferSize}));
 await page.locator('[data-contact-open]').tap();await page.locator('#contact-dialog [data-close]').tap();await page.locator('.menu-toggle').tap();await page.locator('#menu-dialog a[href="#work"]').tap();
 for(const img of await page.locator('main img').all()){await img.scrollIntoViewIfNeeded();await img.evaluate(i=>i.decode());}await page.waitForTimeout(1000);
 const data=await page.evaluate(()=>({...qaPerf,resourceBytes:performance.getEntriesByType('resource').reduce((a,e)=>a+e.transferSize,0)}));runs.push({run,...data,maxObservedInteractionMs:Math.max(0,...data.events.map(e=>e.duration)),initial});console.log(JSON.stringify({run,lcp:data.lcp,cls:data.cls,maxInteraction:Math.max(0,...data.events.map(e=>e.duration)),bytes:data.resourceBytes}));await context.close();
}await browser.close();fs.mkdirSync(`qa/${label}`,{recursive:true});fs.writeFileSync(`qa/${label}/performance.json`,JSON.stringify({base,date:new Date().toISOString(),environment:'Chrome / Windows, 390×844 DPR1 touch, cold cache, 4× CPU, 80ms latency, 200KiB/s down, 100KiB/s up',scope:'Lab only. Event Timing interaction durations are diagnostic samples, not field INP. CLS is sum of observed non-input shifts in this short session.',runs},null,2));})().catch(e=>{console.error(e);process.exit(1)});
